/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAPIDocs: typeof import('./dev/docs/BaseAPIDocs.md')['default']
    ButtonDocs: typeof import('./dev/docs/ButtonDocs.md')['default']
    FlashDocs: typeof import('./dev/docs/FlashDocs.md')['default']
    StackingContextDocs: typeof import('./dev/docs/StackingContextDocs.md')['default']
    UseBaseAPIDocs: typeof import('./dev/docs/UseBaseAPIDocs.md')['default']
    UseTabHistoryDocs: typeof import('./dev/docs/UseTabHistoryDocs.md')['default']
    UseUrlSearchParamsDocs: typeof import('./dev/docs/UseUrlSearchParamsDocs.md')['default']
  }
}
