name: Publish to npm + GitHub Pages

# This workflow will run on any pushed to the main branch and on any pull requests targeting main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install client dependencies
        run: |
          npm install
          npm run build:deploy

      # - name: Publish to npm
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      #     npm publish --access public

      # - name: Build for GitHub Pages
      #   run: | 
      #     npm install
      #     npm run build:deploy

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
