name: Publish to npm + GitHub Pages

# This workflow will run on any pushed to the main branch and on any pull requests targeting main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16.9.1
        uses: actions/setup-node@v1
        with:
          node-version: "16.9.1"

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install client dependencies
        run: |
          npm ci
          npm run build

      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm publish --access public

      - name: Build for GitHub Pages
        run: npm run build:docs

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: trees
