name: Publish to npm

# This workflow will run on any pushed to the main branch and on any pull requests targeting main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.1'

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-
      - name: Install client dependencies
        run: |
          npm install
          npm run build
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm publish --access public
