name: Test Build

# This workflow will run on any pushed branch except main
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Node version
        run: node --version && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build Library
        run: npm run build

      - name: Build Docs
        run: npm run build:docs
